PHP Composer definition file
rciam/simplesamlphp-module-authorcid pull request #1
Opened 2017-08-07 07:49 UTC by tauceti2

2017-09-02 14:38 UTC, NicolasLiampotis commented on composer.json
> +         "email": "nliam@admin.grnet.gr"
Could you please change the email address to `nliam@grnet.gr`?

2017-09-02 14:39 UTC, NicolasLiampotis requested changes
Many thanks for this! Will merge as soon as you update the email address.

Again, thanks!

2017-09-03 06:01 UTC, tauceti2 commented
Done.

2017-09-03 23:06 UTC, NicolasLiampotis approved these changes

2017-09-03 23:12 UTC, merged